version: '3'

services:

  mongo_db:
    image: mongo:6.0
    container_name: mongo-db
    environment:
        - MONGO_INITDB_ROOT_USERNAME=${DB_USER}
        - MONGO_INITDB_ROOT_PASSWORD=${DB_PASS}
        - MONGO_INITDB_DATABASE=${DB_NAME}
    ports:
      - "27017:27017"
    volumes:
      - db:/data/db
    networks:
      - users-microservice

  server:
    restart: always
    container_name: users-microservice-backend
    image: users-microservice-backend:latest
    build: 
      context: .
      dockerfile: server/docker/Dockerfile
    environment:
      DB_URI: mongodb://mongo-db:27017
    expose:
      - 8000
    depends_on:
      - mongo_db
    networks:
      - users-microservice

  nginx:
    restart: always
    container_name: users-microservice-nginx
    image: users-microservice-nginx:latest
    build:
        context: ./nginx
        dockerfile: ./Dockerfile
    ports:
      - 80:80
    depends_on:
      - server
      - mongo_db
    networks:
      - users-microservice

volumes:
  db:
    name: users-microservice-db

networks:
  users-microservice:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.4.0.0/16