name: Run tests

on: [pull_request]

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Make envfile
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_DB_URI: ${{ vars.MONGODB_URI }}
          envkey_DB_NAME: ${{ vars.MONGODB_NAME }}
          envkey_DB_USER: ${{ vars.MONGODB_USER }}
          envkey_DB_PASS: ${{ secrets.MONGODB_PASSWORD }}
          envkey_PORT: ${{ vars.PORT }}
          envkey_NODE_ENV: ${{ vars.NODE_ENV }}
          envkey_AUTH_DB: ${{ vars.AUTH_DB }}
          envkey_JWT_SECRET: ${{ secrets.JWT_SECRET }}
          envkey_JWT_EXPIRATION_TIME: ${{ vars.JWT_EXPIRATION_TIME }}
          envkey_SALT_ROUNDS: ${{ vars.SALT_ROUNDS }}
          envkey_RESET_DB_ON_EACH_RELOAD: ${{ vars.RESET_DB_ON_EACH_RELOAD }}
          envkey_ADMIN_USERNAME: ${{ vars.ADMIN_USERNAME }}
          envkey_ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
          envkey_ADMIN_EMAIL: ${{ vars.ADMIN_EMAIL }}
          envkey_TESTING_API_BASE_URL: ${{ vars.TESTING_API_BASE_URL }}
          envkey_BASE_URL: ${{ vars.BASE_URL }}
          envkey_DB_TEST_NAME: ${{ vars.MONGODB_TEST_NAME }}
          directory: ./server
          file_name: .env
          fail_on_empty: false
          sort_keys: false

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.10.0
        with:
          mongodb-version: ${{ vars.MONGODB_VERSION }}
          mongodb-username: ${{ vars.MONGODB_USER }}
          mongodb-password: ${{ secrets.MONGODB_PASSWORD }}
          mongodb-db: ${{ vars.MONGODB_NAME }}
          mongodb-port: ${{ vars.MONGODB_PORT }}
        
      - name: Install dependencies
        working-directory: ./server
        run: npm ci 

      - name: Build project
        working-directory: ./server
        run: npm run build

      - name: Start server
        working-directory: ./server
        run: npm run start --run-tests&

      - name: Run tests
        working-directory: ./server
        run: npm test